project:
  type: website
  output-dir: docs

website:
  title: "The Greatest International Striker"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Analysis"
        href: analysis.qmd
      - text: "Model"
        href: model.qmd
      - text: "About"
        href: about.qmd
        file: about.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Report"
        contents:
          - analysis.qmd
          - model.qmd
format:
  html:
    theme: cosmo
    toc: true
